apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: brxm-repo-maintainer
spec:
  schedule: "*/2 * * * *" #every 2 minutes, only for local testing, production env will most likely need something like once or twice a day
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: brxm-repo-maintainer
          containers:
            - name: brxm-mysql-repo-maintainer
              image: bloomreach/xm-mysql-repo-maintainer
              env:
                - name: APP_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: BRXM_SELECTOR
                  value: "app=brxm-cms-site"
                - name: MYSQL_DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: name
                      name: my-mysql-variables
                - name: "MYSQL_DB_PORT"
                  value: "3306"
                - name: MYSQL_DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: mysqlDatabase
                      name: my-mysql-variables
                - name: MYSQL_DB_USER
                  valueFrom:
                    configMapKeyRef:
                      key: mysqlUser
                      name: my-mysql-variables
                - name: MYSQL_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: mysql-password
                      name: my-mysql
          restartPolicy: OnFailure